### ISSUE TITLE
Interface should have empty method body

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#96]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/Collided.java#L8

**Comment by BhavnoorSaroya** [comment]
Interfaces are able to define a default version of a method, so that implementing classes have the choice of redefining the default implementation or using the default implementation. This comes with the benefit that while a class can only inherit from one superclass(extends) it can implement multiple interfaces.
